name: Discord notifications

on: [push]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Config Insomnia mise à jour sur GitHub.'
